CREATE TABLE CAUCET (
	"NUMBER" INTEGER NOT NULL PRIMARY KEY,
	PROTO VARCHAR,
	PRNUM INTEGER,
	MEANING VARCHAR,
	NAKH VARCHAR,
	NAKHNUM INTEGER,
	AAND VARCHAR,
	AANDNUM INTEGER,
	CEZ VARCHAR,
	CEZNUM INTEGER,
	LAK VARCHAR,
	LAKNUM INTEGER,
	DARG VARCHAR,
	DARGNUM INTEGER,
	LEZG VARCHAR,
	LEZGNUM INTEGER,
	KHIN VARCHAR,
	KHINNUM INTEGER,
	COMMENT VARCHAR,
);

CREATE TABLE AANDET (
	"NUMBER" INTEGER NOT NULL PRIMARY KEY,
	PROTO VARCHAR,
	PRNUM INTEGER,
	MEANING VARCHAR,
	AVA VARCHAR,
	AVC VARCHAR,
	"AND" VARCHAR,
	AKV VARCHAR,
	CHM VARCHAR,
	TND VARCHAR,
	KRT VARCHAR,
	BTL VARCHAR,
	BGV VARCHAR,
	GDB VARCHAR,
	COMMENT VARCHAR
);

CREATE TABLE CEZET (
	"NUMBER" INTEGER NOT NULL PRIMARY KEY,
	PROTO VARCHAR,
	PRNUM INTEGER, 
	MEANING VARCHAR,
	CEZ VARCHAR,
	GIN VARCHAR,
	KHV VARCHAR,
	INH VARCHAR,
	BZT VARCHAR,
	GNZ VARCHAR,
	COMMENT VARCHAR
);

CREATE TABLE DARGET (
	"NUMBER" INTEGER NOT NULL PRIMARY KEY,
	PROTO VARCHAR,
	PRNUM INTEGER,
	MEANING VARCHAR,
	DRG VARCHAR,
	CHR VARCHAR,
	COMMENT VARCHAR
);

CREATE TABLE KHINET (
	"NUMBER" INTEGER NOT NULL PRIMARY KEY,
	PROTO VARCHAR,
	PRNUM INTEGER,
	MEANING VARCHAR,
	KHI VARCHAR,
	COMMENT VARCHAR
);

CREATE TABLE LAKET (
	"NUMBER" INTEGER NOT NULL PRIMARY KEY,
	PROTO VARCHAR,
	PRNUM INTEGER,
	MEANING VARCHAR,
	LAK VARCHAR,
	COMMENT VARCHAR
);

CREATE TABLE LEZGET (
	"NUMBER" INTEGER NOT NULL PRIMARY KEY,
	PROTO VARCHAR,
	PRNUM INTEGER,
	MEANING VARCHAR,
	LZG VARCHAR,
	TAB  VARCHAR,
	AGU  VARCHAR,
	RUT  VARCHAR,
	CAK  VARCHAR,
	KRZ VARCHAR,
	BUD VARCHAR,
	ARC VARCHAR,
	UDI VARCHAR,
	COMMENT VARCHAR
);

CREATE TABLE NAKHET (
	"NUMBER" INTEGER NOT NULL PRIMARY KEY,
	PROTO VARCHAR,
	PRNUM INTEGER,
	MEANING VARCHAR,
	CHE VARCHAR,
	ING VARCHAR,
	BCB VARCHAR,
	COMMENT VARCHAR
);